import os
import requests
import urllib.parse
import time
import random

def generate_huggingface_cascade(prompt, output_path):
    print("      [Tier 1: HuggingFace] Attempting AI generation...")
    hf_token = os.environ.get("HF_TOKEN")
    if not hf_token: return False, "No Token"
        
    # 🚨 THE CASCADE: If FLUX is out of quota (402), it instantly falls back to SDXL
    models = [
        "black-forest-labs/FLUX.1-schnell",
        "stabilityai/stable-diffusion-xl-base-1.0"
    ]
    
    headers = {"Authorization": f"Bearer {hf_token}", "Content-Type": "application/json"}
    payload = {"inputs": f"{prompt}, vertical 9:16 format, masterpiece"}
    
    for model in models:
        url = f"https://api-inference.huggingface.co/models/{model}"
        short_name = model.split('/')[-1]
        print(f"      -> Routing to {short_name}...")
        
        try:
            response = requests.post(url, headers=headers, json=payload, timeout=60)
            if response.status_code == 200:
                with open(output_path, 'wb') as f: 
                    f.write(response.content)
                return True, f"HF ({short_name})"
            elif response.status_code == 402:
                print(f"      ⚠️ {short_name} out of free quota. Switching models...")
                continue # Instantly try the next model
            elif response.status_code == 503:
                print(f"      💤 {short_name} asleep. Waiting 20s...")
                time.sleep(20)
                response = requests.post(url, headers=headers, json=payload, timeout=60)
                if response.status_code == 200:
                    with open(output_path, 'wb') as f: f.write(response.content)
                    return True, f"HF ({short_name})"
        except: pass
            
    return False, "HF Models Exhausted/Blocked"

def fallback_pexels_image(search_query, output_path):
    print(f"      [Tier 3: Pexels] AI Blocked. Searching strictly for: '{search_query}'...")
    api_key = os.environ.get("PEXELS_API_KEY")
    if not api_key: return False, "No Key"
        
    try:
        # 🚨 PEXELS FIX: Uses the dedicated 1-2 word noun generated by the AI
        query = urllib.parse.quote(search_query) 
        url = f"https://api.pexels.com/v1/search?query={query}&orientation=portrait&per_page=15"
        headers = {"Authorization": api_key}
        res = requests.get(url, headers=headers, timeout=15).json()
        
        if res.get('photos'):
            photo = random.choice(res['photos'])
            img_url = photo['src']['large2x']
            img_data = requests.get(img_url, timeout=15).content
            with open(output_path, 'wb') as f: f.write(img_data)
            return True, ""
    except Exception as e: 
        return False, "API Error"
    return False, "No images found"

def fetch_scene_images(prompts_list, pexels_queries, base_filename="temp_scene"):
    print(f"🖼️ [VISUALS] Sourcing {len(prompts_list)} scene images via Decoupled 3-Tier System...")
    successful_images = []
    
    tier1_active = True
    final_provider = "Unknown"
    
    for i, prompt in enumerate(prompts_list):
        output_path = f"{base_filename}_{i}.jpg"
        print(f"\n   -> Scene {i+1} Prompt: {prompt[:40]}...")
        
        success = False
        
        # 1. Tier 1: Hugging Face Cascade
        if tier1_active:
            success, provider_msg = generate_huggingface_cascade(prompt, output_path)
            if success: 
                final_provider = provider_msg
            else:
                print(f"      🚨 [VISUALS] Tier 1 Failed ({provider_msg}). Disabling for remainder of run.")
                tier1_active = False 
        else:
            print("      [Tier 1: Hugging Face] Skipped (Previously Blocked)")

        # 2. Tier 3: Pexels Dedicated Query Fallback
        if not success:
            success, err = fallback_pexels_image(pexels_queries[i], output_path)
            if success: 
                final_provider = "Pexels Stock Fallback"
            
        if success:
            successful_images.append(output_path)
            print(f"   ✅ Scene {i+1} saved successfully.")
        else:
            print(f"   ❌ Scene {i+1} failed completely.")
            
        print("   ⏳ Pacing generation engines (Sleeping 3s)...")
        time.sleep(3) 
        
    return successful_images, final_provider
