# scripts/generate_thumbnail.py — Ghost Engine
"""
Generates a custom YouTube thumbnail for each video.

Strategy:
  1. Take the first scene image (already generated by generate_visuals.py)
  2. Crop/resize to 1280x720 (standard YouTube thumbnail)
  3. Add a dark gradient overlay at the bottom for text contrast
  4. Overlay the video title in bold white text (max 5 words)
  5. Save as thumbnail.jpg

If PIL/Pillow is not available or the source image is missing, returns None
silently — the pipeline continues without a thumbnail rather than failing.

Thumbnail upload to YouTube:
  - Requires youtube.force-ssl OR youtube scope.
  - If the upload fails with 403 (scope missing, or channel not yet verified
    for custom thumbnails — needs 10K+ lifetime views), it is caught and
    logged. The video remains vaulted successfully without a custom thumbnail.
"""
import os
import re
import textwrap
import traceback


def _get_font(size: int):
    """Try to load a bold system font. Falls back to PIL default if none found."""
    try:
        from PIL import ImageFont
        candidates = [
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
            "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
            "/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf",
        ]
        for path in candidates:
            if os.path.exists(path):
                return ImageFont.truetype(path, size)
        return ImageFont.load_default()
    except Exception:
        return None


def _clean_title_for_thumbnail(title: str, max_words: int = 5) -> str:
    """Extract impactful words from title for overlay. Strips hashtags, uppercases."""
    clean = re.sub(r'#\S+', '', title).strip()
    clean = re.sub(r'[^\w\s\-:!?.,\'"()]', '', clean).strip()
    words = clean.split()
    if len(words) > max_words:
        words = words[:max_words]
    return " ".join(words).upper()


def generate_thumbnail(image_paths: list, title: str, output_path: str = "thumbnail.jpg"):
    """
    Generate a YouTube thumbnail from the first scene image.

    Returns path to saved thumbnail, or None if generation failed.
    Pipeline continues without thumbnail on failure.
    """
    if not image_paths:
        print("⚠️ [THUMBNAIL] No scene images available — skipping.")
        return None

    source_image = image_paths[0]
    if not os.path.exists(source_image):
        print(f"⚠️ [THUMBNAIL] Source image not found: {source_image}")
        return None

    try:
        from PIL import Image, ImageDraw

        # 1. Load + crop to 16:9 from centre (scene images are 9:16 vertical)
        img = Image.open(source_image).convert("RGB")
        orig_w, orig_h = img.size
        target_ratio = 16 / 9

        if orig_w / orig_h < target_ratio:
            new_h = int(orig_w / target_ratio)
            top   = (orig_h - new_h) // 3
            img   = img.crop((0, top, orig_w, top + new_h))
        else:
            new_w = int(orig_h * target_ratio)
            left  = (orig_w - new_w) // 2
            img   = img.crop((left, 0, left + new_w, orig_h))

        img = img.resize((1280, 720), Image.LANCZOS)

        # 2. Dark gradient overlay at bottom for text contrast
        overlay = Image.new("RGBA", (1280, 720), (0, 0, 0, 0))
        draw    = ImageDraw.Draw(overlay)
        for y in range(360, 720):
            alpha = int(180 * ((y - 360) / 360))
            draw.line([(0, y), (1280, y)], fill=(0, 0, 0, alpha))

        img = Image.alpha_composite(img.convert("RGBA"), overlay).convert("RGB")

        # 3. Bold text overlay
        draw         = ImageDraw.Draw(img)
        display_text = _clean_title_for_thumbnail(title, max_words=5)
        font         = _get_font(72) or _get_font(48)

        if font and display_text:
            wrapped = textwrap.fill(display_text, width=18)
            lines   = wrapped.split("\n")[:2]
            y_start = 580 - (len(lines) * 80)
            for i, line in enumerate(lines):
                y = y_start + (i * 85)
                draw.text((42, y + 4), line, font=font, fill=(0, 0, 0, 200))  # shadow
                draw.text((40, y),     line, font=font, fill=(255, 255, 255)) # text

        # 4. Save
        img.save(output_path, "JPEG", quality=92, optimize=True)
        size_kb = os.path.getsize(output_path) // 1024
        print(f"🖼️ [THUMBNAIL] Generated: {output_path} ({size_kb} KB)")
        return output_path

    except Exception:
        print(f"⚠️ [THUMBNAIL] Generation failed:\n{traceback.format_exc()}")
        return None


def upload_thumbnail(youtube, video_id: str, thumbnail_path: str) -> bool:
    """
    Upload custom thumbnail to YouTube. Requires youtube.force-ssl scope OR
    channel verification (10K+ lifetime views). Returns False on any failure
    without crashing the pipeline.
    """
    if not youtube or not video_id or not thumbnail_path:
        return False
    if not os.path.exists(thumbnail_path):
        print(f"⚠️ [THUMBNAIL] File not found for upload: {thumbnail_path}")
        return False

    try:
        from googleapiclient.http import MediaFileUpload
        media = MediaFileUpload(thumbnail_path, mimetype="image/jpeg")
        youtube.thumbnails().set(videoId=video_id, media_body=media).execute()
        print(f"✅ [THUMBNAIL] Custom thumbnail uploaded for {video_id}")
        return True
    except Exception as e:
        err_str = str(e).lower()
        if "403" in err_str or "forbidden" in err_str or "insufficient" in err_str:
            print(
                f"⚠️ [THUMBNAIL] Skipped — channel needs 10K+ lifetime views for custom "
                f"thumbnails. Will retry automatically once threshold is reached."
            )
        else:
            print(f"⚠️ [THUMBNAIL] Upload failed (non-fatal): {e}")
        return False
