name: Test Voice Engine

on:
  workflow_dispatch:

jobs:
  test-tts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install edge-tts

      - name: Generate Audio
        run: python src/generators/audio_generator.py

      - name: Upload Audio Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-voice-test
          path: test_audio.mp3
